### ISSUE TITLE
1D

### ISSUE THREAD

**Issue by damienbouffard** [eawag-surface-waters-research/alplakes-react#29]
Showing the last week heat map is perhaps not the best front image to display. I would recommend to switch to yearly heatmap as default information for 1D model

**Comment by f-baerenbold** [comment]
In addition, could the surface temperature of the current year be included into the "historic temperature trend" plot in the bottom? Also, the plot does not show a "trend", but rather "historic surface temperature evolution". 

And the x-axis should not contain the year if I understand the plot correctly. It should be DOY, right?

**Comment by JamesRunnalls** [comment]
> In addition, could the surface temperature of the current year be included into the "historic temperature trend" plot in the bottom? Also, the plot does not show a "trend", but rather "historic surface temperature evolution".
> 
> And the x-axis should not contain the year if I understand the plot correctly. It should be DOY, right?

I can change the label and will add the surface temperature.

**Comment by f-baerenbold** [comment]
Personally, I would suggest the previous 1 year I think.

**Comment by damienbouffard** [comment]
You can also just show the "average DOI temperature" as first image to display if you prefer (or if it is easier in term of data volume). By the way, I could not see the current year displayed on such DOI-based plot

**Comment by f-baerenbold** [comment]
Looks good now. Maybe write "Surface temperature" instead of just "Temperature" on the y-axis label. You could also add the quantiles to the legend to be more clear what the grey tones and I would also add the time frame somewhere on which the quantiles are based.
