### ISSUE TITLE
Learn More & Medium

### ISSUE THREAD

**Issue by damienbouffard** [eawag-surface-waters-research/alplakes-react#31]
In principle, I do not oppose to using Medium to provide more details. But this point needs to be discussed between JR, DO, MS and DB.

main issue (unless I am wrong) --> you need to pay to have full access to Medium. This can't be a valid option for an open access framework such as Alplakes. 

I understand your motivations for publishing into Medium so we should find an acceptable solution

I would like to be involved in the articles. Let's discuss when you are back

**Comment by JamesRunnalls** [comment]
You need to pay to have full access to Medium, however, as we wouldn't want to make money from our articles then they are free and open for anyone to read. I don't have any particular attachment to using Medium, it is just where I have seen similar content in the past.

I agree it would be good to discuss all together about what this should look like, do you want me to set up a meeting?

**Comment by damienbouffard** [comment]
sure. thanks

**Comment by JamesRunnalls** [comment]
About page has been updated and links to Medium articles has been removed until this can be decided.
