### ISSUE TITLE
Main map

### ISSUE THREAD

**Issue by f-baerenbold** [eawag-surface-waters-research/alplakes-react#34]
- Maybe write "zoom in to see more lakes"?
- Color code seems to be "discrete" instead of continuous. Maybe also add the colorbar.
- Are temperatures on the front page from 1D or 3D if both are available?

**Comment by JamesRunnalls** [comment]
Nice idea I will add the prompt to zoom in.

It is discrete and matches BAFU hydrodaten, I went for discrete as it's much easier to get an overview of which lakes are colder/ warmer than with a continuous scale. Like with hydrodaten I could add a pop up colorbar though I am not sure it is necessary when the temperature values are displayed.

Currently they are just 1D, or 3D if no 1D available

**Comment by tdoda** [comment]
Even if the temperature is displayed, I still think that it would be nice to have a a pop up colorbar (for example if we click on the temperature symbol).

**Comment by JamesRunnalls** [comment]
5b08f8c
