### ISSUE TITLE
Incoherence of model output numbers

### ISSUE THREAD

**Issue by f-baerenbold** [eawag-surface-waters-research/alplakes-react#35]
Example Lake Lucerne

Main map shows 12.6 °C at the surface and 16 °C in 5 days.

If I click on the lake, the heat map of the 1D model shows 9.8 °C today at the surface and 11.44 °C in 5 days.

**Comment by f-baerenbold** [comment]
The line graph (annual course) is also not complete. Quantiles are missing.

**Comment by JamesRunnalls** [comment]
> The line graph (annual course) is also not complete. Quantiles are missing.

Fixed

**Comment by f-baerenbold** [comment]
The line graph actually looks very unrealistic with maximum temperatures above 30 °C for Lake Lucerne. This is impossible. The dark orange line, however, looks realistic.

**Comment by f-baerenbold** [comment]
On the old simstrat webpage, the simulations look fine for Lake Lucerne. Also, there seems to be an issue with the old webpage because it is not loading correctly and the simulations were not done this night.
