### ISSUE TITLE
3D particle tracking

### ISSUE THREAD

**Issue by tdoda** [eawag-surface-waters-research/alplakes-react#38]
The depth value is not shown above the cursor (unlike for temperature and current data). See the attached screenshot.
![image](https://github.com/eawag-surface-waters-research/alplakes-react/assets/77243929/308da23c-19bc-4d68-80e4-a8dce3d1f1c8)

**Comment by JamesRunnalls** [comment]
b064c45ac44c4dde481652017e712ccbaf91e193
