### ISSUE TITLE
Oxygen number displayed on main map

### ISSUE THREAD

**Issue by f-baerenbold** [eawag-surface-waters-research/alplakes-react#41]
Currently, the oxygen saturation of the lowest 5 m of each lake is displayed on the main map. This value may not be very representative of the whole hypolimnion, especially for very deep lakes.

Another option would be to display "mean hypolimnetic oxygen concentration" (or saturation) below 15 m, meaning the concentration (or saturation) of the water below 15 m and averaged using bathymetry.

**Comment by JamesRunnalls** [comment]
What do you mean by "averaged using bathymetry"?

**Comment by f-baerenbold** [comment]
Volume averaged; not just depth-averaged.

**Comment by JamesRunnalls** [comment]
Not including oxygen on homepage
